apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-api-config
  namespace: microservices
  labels:
    app: notifications-api
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:80"