apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-config
  namespace: microservices
  labels:
    app: catalog-api
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:80"