apiVersion: v1
kind: Secret
metadata:
  name: catalogapi-secret
  namespace: microservices
type: Opaque
stringData:
  ConnectionStrings__CatalogDb: "Server=sql-catalog,1433;Database=CatalogDb;User Id=sa;Password=StrongPassword!123;TrustServerCertificate=True;"
